import type { Risk, Event, Stakeholder, Deliverable, Project } from "@shared/schema";
import { format, subDays } from "date-fns";

export interface RiskReportSection {
  title: string;
  content: string;
}

export interface RiskReportData {
  project: Project;
  periodStart: Date;
  periodEnd: Date;
  risks: Risk[];
  recentEvents: Event[];
  stakeholders: Stakeholder[];
  deliverables: Deliverable[];
}

export interface BuiltRiskReport {
  sections: RiskReportSection[];
  riskSummary: {
    critical: number;
    high: number;
    medium: number;
    low: number;
    total: number;
  };
  emailSubject: string;
}

function getRiskLevel(score: number | null): "critical" | "high" | "medium" | "low" {
  if (!score) return "low";
  if (score >= 20) return "critical";
  if (score >= 12) return "high";
  if (score >= 6) return "medium";
  return "low";
}

function formatRiskForReport(risk: Risk): string {
  const level = getRiskLevel(risk.score);
  const levelLabel = level.charAt(0).toUpperCase() + level.slice(1);
  const statusLabel = risk.status.charAt(0).toUpperCase() + risk.status.slice(1);
  
  let riskLine = `- **${risk.title}** (${levelLabel}, L${risk.likelihood}×I${risk.impact}=${risk.score ?? "?"})\n`;
  riskLine += `  - Category: ${risk.category.charAt(0).toUpperCase() + risk.category.slice(1)}\n`;
  riskLine += `  - Status: ${statusLabel}\n`;
  if (risk.mitigation) {
    riskLine += `  - Mitigation: ${risk.mitigation}\n`;
  }
  if (risk.owner) {
    riskLine += `  - Owner: ${risk.owner}\n`;
  }
  return riskLine;
}

function buildRiskMatrix(risks: Risk[]): string {
  const rows: string[] = [];
  rows.push("| Likelihood \\ Impact | 1 | 2 | 3 | 4 | 5 |");
  rows.push("|---------------------|---|---|---|---|---|");
  
  for (let likelihood = 5; likelihood >= 1; likelihood--) {
    const row: string[] = [`| ${likelihood} |`];
    for (let impact = 1; impact <= 5; impact++) {
      const count = risks.filter(r => r.likelihood === likelihood && r.impact === impact).length;
      row.push(count > 0 ? ` **${count}** |` : " - |");
    }
    rows.push(row.join(""));
  }
  
  return rows.join("\n");
}

export function buildRiskReport(data: RiskReportData): BuiltRiskReport {
  const { project, periodStart, periodEnd, risks, recentEvents, stakeholders, deliverables } = data;
  
  const sections: RiskReportSection[] = [];
  
  const criticalRisks = risks.filter(r => getRiskLevel(r.score) === "critical");
  const highRisks = risks.filter(r => getRiskLevel(r.score) === "high");
  const mediumRisks = risks.filter(r => getRiskLevel(r.score) === "medium");
  const lowRisks = risks.filter(r => getRiskLevel(r.score) === "low");
  
  const riskSummary = {
    critical: criticalRisks.length,
    high: highRisks.length,
    medium: mediumRisks.length,
    low: lowRisks.length,
    total: risks.length,
  };
  
  const periodStartFormatted = format(periodStart, "MMM d, yyyy");
  const periodEndFormatted = format(periodEnd, "MMM d, yyyy");
  
  sections.push({
    title: "Report Header",
    content: `# Risk Report: ${project.name}

**Client:** ${project.clientName || "N/A"}  
**Reporting Period:** ${periodStartFormatted} - ${periodEndFormatted}  
**Generated:** ${format(new Date(), "MMM d, yyyy 'at' h:mm a")}  
**Phase:** ${project.phase.charAt(0).toUpperCase() + project.phase.slice(1)}

---`
  });
  
  sections.push({
    title: "Executive Summary",
    content: `## Executive Summary

**Risk Overview:**
- Critical Risks: ${criticalRisks.length}
- High Risks: ${highRisks.length}
- Medium Risks: ${mediumRisks.length}
- Low Risks: ${lowRisks.length}

${criticalRisks.length > 0 ? `⚠️ **Attention Required:** ${criticalRisks.length} critical risk(s) require immediate sponsor attention.` : "✅ No critical risks currently identified."}

${highRisks.length >= 3 ? `📊 **Elevated Risk Profile:** Multiple high-severity risks warrant close monitoring.` : ""}

<!-- AI_NARRATIVE_PLACEHOLDER: Executive narrative to be generated by AI -->`
  });
  
  sections.push({
    title: "Risk Matrix",
    content: `## Risk Heat Map

${buildRiskMatrix(risks)}

*Cells show count of risks at each Likelihood × Impact combination.*`
  });
  
  if (criticalRisks.length > 0) {
    sections.push({
      title: "Critical Risks",
      content: `## Critical Risks (Score ≥ 20)

${criticalRisks.map(formatRiskForReport).join("\n")}`
    });
  }
  
  if (highRisks.length > 0) {
    sections.push({
      title: "High Risks",
      content: `## High Risks (Score 12-19)

${highRisks.map(formatRiskForReport).join("\n")}`
    });
  }
  
  if (mediumRisks.length > 0) {
    sections.push({
      title: "Medium Risks",
      content: `## Medium Risks (Score 6-11)

${mediumRisks.map(formatRiskForReport).join("\n")}`
    });
  }
  
  if (lowRisks.length > 0) {
    sections.push({
      title: "Low Risks",
      content: `## Low Risks (Score < 6)

${lowRisks.map(formatRiskForReport).join("\n")}`
    });
  }
  
  const activeDeliverables = deliverables.filter(d => d.status === "in_progress" || d.status === "blocked");
  if (activeDeliverables.length > 0) {
    sections.push({
      title: "Deliverable Context",
      content: `## Related Deliverables

| Deliverable | Status | Progress |
|-------------|--------|----------|
${activeDeliverables.map(d => `| ${d.name} | ${d.status} | ${Math.round(d.progress * 100)}% |`).join("\n")}`
    });
  }
  
  const recentMeetings = recentEvents.filter(e => e.type === "meeting");
  const recentDecisions = recentEvents.filter(e => e.type === "decision");
  
  if (recentMeetings.length > 0 || recentDecisions.length > 0) {
    let contextContent = `## Recent Context\n\n`;
    
    if (recentMeetings.length > 0) {
      contextContent += `### Recent Meetings\n`;
      recentMeetings.slice(0, 5).forEach(m => {
        contextContent += `- **${m.title}** (${format(new Date(m.occurredAt), "MMM d")})\n`;
      });
      contextContent += "\n";
    }
    
    if (recentDecisions.length > 0) {
      contextContent += `### Recent Decisions\n`;
      recentDecisions.slice(0, 5).forEach(d => {
        contextContent += `- ${d.title} (${format(new Date(d.occurredAt), "MMM d")})\n`;
      });
    }
    
    sections.push({
      title: "Recent Context",
      content: contextContent
    });
  }
  
  const sponsors = stakeholders.filter(s => s.influence === "high");
  if (sponsors.length > 0) {
    sections.push({
      title: "Key Stakeholders",
      content: `## Key Stakeholders

| Name | Role | Support Level |
|------|------|---------------|
${sponsors.map(s => `| ${s.name} | ${s.role || "—"} | ${s.supportLevel || "—"} |`).join("\n")}`
    });
  }
  
  sections.push({
    title: "Next Steps",
    content: `## Recommended Next Steps

<!-- AI_RECOMMENDATIONS_PLACEHOLDER: AI-generated recommendations based on risk analysis -->

---

*This report was generated by VANTIS Mission Control. For questions, contact the project lead.*`
  });
  
  const urgencyPrefix = criticalRisks.length > 0 ? "[ACTION REQUIRED] " : "";
  const emailSubject = `${urgencyPrefix}Risk Report: ${project.name} (${periodEndFormatted})`;
  
  return {
    sections,
    riskSummary,
    emailSubject
  };
}

export function sectionsToMarkdown(sections: RiskReportSection[]): string {
  return sections.map(s => s.content).join("\n\n");
}

export function markdownToHtml(markdown: string): string {
  let html = markdown;
  
  html = html.replace(/^# (.+)$/gm, '<h1>$1</h1>');
  html = html.replace(/^## (.+)$/gm, '<h2>$1</h2>');
  html = html.replace(/^### (.+)$/gm, '<h3>$1</h3>');
  
  html = html.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
  html = html.replace(/\*(.+?)\*/g, '<em>$1</em>');
  
  html = html.replace(/^- (.+)$/gm, '<li>$1</li>');
  html = html.replace(/(<li>.*<\/li>\n)+/g, (match) => `<ul>\n${match}</ul>\n`);
  
  const tableRegex = /\|(.+)\|\n\|[-|]+\|\n((?:\|.+\|\n)+)/g;
  html = html.replace(tableRegex, (match, header, rows) => {
    const headerCells = header.split('|').filter((c: string) => c.trim()).map((c: string) => `<th>${c.trim()}</th>`).join('');
    const rowLines = rows.trim().split('\n');
    const bodyRows = rowLines.map((row: string) => {
      const cells = row.split('|').filter((c: string) => c.trim()).map((c: string) => `<td>${c.trim()}</td>`).join('');
      return `<tr>${cells}</tr>`;
    }).join('\n');
    return `<table class="report-table">\n<thead><tr>${headerCells}</tr></thead>\n<tbody>\n${bodyRows}\n</tbody>\n</table>\n`;
  });
  
  html = html.replace(/---/g, '<hr>');
  
  html = html.replace(/\n\n/g, '</p><p>');
  html = `<p>${html}</p>`;
  html = html.replace(/<p><(h[123]|ul|table|hr)/g, '<$1');
  html = html.replace(/<\/(h[123]|ul|table)><\/p>/g, '</$1>');
  html = html.replace(/<p><\/p>/g, '');
  
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; line-height: 1.6; }
    h1 { color: #1a1a2e; border-bottom: 2px solid #6FBFB3; padding-bottom: 10px; }
    h2 { color: #16213e; margin-top: 30px; }
    h3 { color: #0f3460; }
    .report-table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    .report-table th, .report-table td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
    .report-table th { background-color: #6FBFB3; color: white; }
    .report-table tr:nth-child(even) { background-color: #f9f9f9; }
    ul { padding-left: 20px; }
    li { margin: 5px 0; }
    hr { border: none; border-top: 1px solid #ddd; margin: 30px 0; }
    strong { color: #1a1a2e; }
  </style>
</head>
<body>
${html}
</body>
</html>`;
}
